# Generated by Django 4.0.1 on 2022-01-06 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_rename_quatity_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
