# Generated by Django 4.0.1 on 2022-01-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
